apiVersion: v1
kind: Secret
metadata:
  name: {{ include "idempiere.fullname" . }}-secret
  labels:
    {{- include "idempiere.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASS: {{ .Values.secret.dbPass | b64enc | quote }}
  DB_ADMIN_PASS: {{ .Values.secret.dbAdminPass | b64enc | quote }}
  KEY_STORE_PASS: {{ .Values.secret.keyStorePass | b64enc | quote }}
  MAIL_PASS: {{ .Values.secret.mailPass | b64enc | quote }}
